site_name: Maps
site_url: https://maps.centralesupelec.fr/
site_description: Plateforme affichant une carte interactive des campus de CentraleSupélec
site_author: CentraleSupélec

repo_name: CentraleSupelec/maps
repo_url: https://github.com/CentraleSupelec/maps

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  logo: assets/logo.svg
  favicon: assets/favicon.ico
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - "Présentation": "index.md"
